# hmm realy tasty config for realy tasty classification stuff

#the classifier to use
classifier : |
  ensemble.RandomForestClassifier(n_estimators=30, max_features='sqrt', n_jobs=1, max_depth=7, criterion='entropy')


query:

#randomly sample the data if you dont want to use the whole set, -1 for all stuff
sample : -1


# define th number of cross validations to perform
num_cross_validations : 15

#specify the variables to train on
training_variables :
  - shower:number_of_pixel
  - shower:width
  - shower:length
  - shower:delta
  - shower:psi
  - shower:skewness
  - shower:kurtosis
  - shower:phi
  - shower:miss
  - shower:r
  - shower:cog:x
  - shower:cog:y
  - shower:size
  - array:num_triggered_telescopes